# Pandas Series

A series is a one dimensional labelled array capable of holding any data type. This axis labels are collectively called the index.

## Creating Series

There are multiple ways to create a pandas series.

In [1]:
!pip install pandas numpy

Requirement already satisfied: pandas in c:\users\dell\documents\sheryians_development\machine learning\ml_env\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\dell\documents\sheryians_development\machine learning\ml_env\lib\site-packages (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\documents\sheryians_development\machine learning\ml_env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\documents\sheryians_development\machine learning\ml_env\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\documents\sheryians_development\machine learning\ml_env\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\dell\documents\sheryians_development\machine learning\ml_env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import numpy as np
import pandas as pd

In [3]:
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={1:10,2:20,3:30}

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

# Data Frames

In [8]:
# Creating a Data Frame

data={
     'Name' : ['John', 'Anna', 'Peter', 'Linda'],
     'Age' : [28,34,29,42],
     'City' : ['New York', 'Paris', 'Berlin', 'London'],
     'Salary' : [65000,70000,62000,85000]
}
df=pd.DataFrame(data)
print(df)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
data_list=[
     ['John',28,'New York',65000],
     ['Anna',34,'Paris',70000],
     ['Peter',29,'Berlin',62000],
     ['Linda',42,'London',85000]
]
df2=pd.DataFrame(data_list)
columns=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=columns)
print(df2)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
# Selection and indexing of columns

df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [11]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [12]:
# Creating a new column
df2["Designation"]=["Doctor","Eng.","Lawyer","Eng."]

In [13]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Lawyer
3  Linda   42    London   85000        Eng.

In [14]:
df2["Designation"]=["Doctor","Eng.","Lawyer","Eng."]

In [22]:
df2.drop(["Description"], axis=1)

KeyError: "['Description'] not found in axis"

In [19]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Lawyer
3  Linda   42    London   85000        Eng.

In [20]:
# Permnently Delete
df2.drop(["Designation"], axis=1,inplace=True)

In [21]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [23]:
#Selecting Rows
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [24]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [26]:
# Selecting subsets of rows and columns
df2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [27]:
# Conditional Selection

# i only want to see whoe age is above 30
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [29]:
# I only want people whose age is above 30 and their city must be paris
df2[(df2["Age"]>30) & (df2["City"]=="Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000