# Pandas Series

A series is a one dimensional labelled array capable of holding any data type. This axis labels are collectively called the index.

## Creating Series

There are multiple ways to create a pandas series.

In [4]:
!pip install pandas numpy

Requirement already satisfied: pandas in c:\users\dell\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\dell\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\dell\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
import numpy as np
import pandas as pd

In [6]:
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={1:10,2:20,3:30}

In [7]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [9]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [10]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

# Data Frames

In [11]:
# Creating a Data Frame

data={
     'Name' : ['John', 'Anna', 'Peter', 'Linda'],
     'Age' : [28,34,29,42],
     'City' : ['New York', 'Paris', 'Berlin', 'London'],
     'Salary' : [65000,70000,62000,85000]
}
df=pd.DataFrame(data)
print(df)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [12]:
data_list=[
     ['John',28,'New York',65000],
     ['Anna',34,'Paris',70000],
     ['Peter',29,'Berlin',62000],
     ['Linda',42,'London',85000]
]
df2=pd.DataFrame(data_list)
columns=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=columns)
print(df2)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [13]:
# Selection and indexing of columns

df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [14]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [15]:
# Creating a new column
df2["Designation"]=["Doctor","Eng.","Lawyer","Eng."]

In [16]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Lawyer
3  Linda   42    London   85000        Eng.

In [17]:
df2["Designation"]=["Doctor","Eng.","Lawyer","Eng."]

In [18]:
df2.drop(["Description"], axis=1)

KeyError: "['Description'] not found in axis"

In [19]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Lawyer
3  Linda   42    London   85000        Eng.

In [20]:
# Permnently Delete
df2.drop(["Designation"], axis=1,inplace=True)

In [21]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [22]:
#Selecting Rows
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [23]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [24]:
# Selecting subsets of rows and columns
df2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [25]:
# Conditional Selection

# i only want to see whoe age is above 30
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [26]:
# I only want people whose age is above 30 and their city must be paris
df2[(df2["Age"]>30) & (df2["City"]=="Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

# Missing Data

In [27]:
#Finding Missing Data
data={
     'A': [1,2,np.nan,4,5],
     'B': [np.nan,2,3,4,5],
     'C': [1,2,3,np.nan,np.nan],
     'D': [1,np.nan,np.nan,np.nan,5]
}
df=pd.DataFrame(data)

In [28]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [29]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [30]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [31]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [32]:
df.dropna(thresh=3)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

In [33]:
df.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [34]:
values={'A':0,'B':100,'C':300,'D':400}
df.fillna(value=values)

     A      B      C      D
0  1.0  100.0    1.0    1.0
1  2.0    2.0    2.0  400.0
2  0.0    3.0    3.0  400.0
3  4.0    4.0  300.0  400.0
4  5.0    5.0  300.0    5.0

# Merging Joining and Concatenation

In [35]:
employees = pd. DataFrame( {
'employee_id': [1, 2, 3, 4, 5],
'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
'department': ['HR', 'IT', 'Finance', 'IT', 'HR']

})

# DataFrame 2: Salary information
salaries = pd.DataFrame ( {
'employee_id': [1, 2, 3, 6, 7],
'salary': [60000, 80000, 65000, 70000, 90000],
'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [36]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [37]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [39]:
pd.merge(employees, salaries, on='employee_id', how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [40]:
pd.merge(employees, salaries, on='employee_id', how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [41]:
pd.merge(employees, salaries, on='employee_id', how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [42]:
pd.merge(employees, salaries, on='employee_id', how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [44]:
df1 = pd.DataFrame({
'A': ['A0', 'A1', 'A2'],
'B': ['B0', 'B1', 'B2'],
'C': ['CO', 'C1', 'C2']
})
df2 = pd.DataFrame({
'A': ['A3', 'A4', 'A5'],
'B': ['B3', 'B4', 'B5'],
'C': ['C3', 'C4', 'C5']
})

In [46]:
pd.concat([df1, df2])

    A   B   C
0  A0  B0  CO
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [47]:
pd.concat([df1, df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  CO  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [49]:
df1 = pd.DataFrame({
'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
'score': [85, 90, 75]
}, index=[2, 3, 4] )

In [50]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [51]:
df2

   score
2     85
3     90
4     75

In [52]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [53]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN