# Pandas Series

A series is a one dimensional labelled array capable of holding any data type. This axis labels are collectively called the index.

## Creating Series

There are multiple ways to create a pandas series.

In [1]:
# !pip install pandas numpy

In [2]:
import numpy as np
import pandas as pd

In [3]:
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={1:10,2:20,3:30}

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

# Data Frames

In [8]:
# Creating a Data Frame

data={
     'Name' : ['John', 'Anna', 'Peter', 'Linda'],
     'Age' : [28,34,29,42],
     'City' : ['New York', 'Paris', 'Berlin', 'London'],
     'Salary' : [65000,70000,62000,85000]
}
df=pd.DataFrame(data)
print(df)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
data_list=[
     ['John',28,'New York',65000],
     ['Anna',34,'Paris',70000],
     ['Peter',29,'Berlin',62000],
     ['Linda',42,'London',85000]
]
df2=pd.DataFrame(data_list)
columns=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=columns)
print(df2)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
# Selection and indexing of columns

df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [11]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [12]:
# Creating a new column
df2["Designation"]=["Doctor","Eng.","Lawyer","Eng."]

In [13]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Lawyer
3  Linda   42    London   85000        Eng.

In [14]:
df2["Designation"]=["Doctor","Eng.","Lawyer","Eng."]

In [15]:
# df2.drop(["Description"], axis=1)

In [16]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Lawyer
3  Linda   42    London   85000        Eng.

In [17]:
# Permnently Delete
df2.drop(["Designation"], axis=1,inplace=True)

In [18]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [19]:
#Selecting Rows
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [20]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [21]:
# Selecting subsets of rows and columns
df2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [22]:
# Conditional Selection

# i only want to see whoe age is above 30
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [23]:
# I only want people whose age is above 30 and their city must be paris
df2[(df2["Age"]>30) & (df2["City"]=="Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

# Missing Data

In [24]:
#Finding Missing Data
data={
     'A': [1,2,np.nan,4,5],
     'B': [np.nan,2,3,4,5],
     'C': [1,2,3,np.nan,np.nan],
     'D': [1,np.nan,np.nan,np.nan,5]
}
df=pd.DataFrame(data)

In [25]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [26]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [27]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [28]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [29]:
df.dropna(thresh=3)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

In [30]:
df.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [31]:
values={'A':0,'B':100,'C':300,'D':400}
df.fillna(value=values)

     A      B      C      D
0  1.0  100.0    1.0    1.0
1  2.0    2.0    2.0  400.0
2  0.0    3.0    3.0  400.0
3  4.0    4.0  300.0  400.0
4  5.0    5.0  300.0    5.0

# Merging Joining and Concatenation

In [32]:
employees = pd. DataFrame( {
'employee_id': [1, 2, 3, 4, 5],
'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
'department': ['HR', 'IT', 'Finance', 'IT', 'HR']

})

# DataFrame 2: Salary information
salaries = pd.DataFrame ( {
'employee_id': [1, 2, 3, 6, 7],
'salary': [60000, 80000, 65000, 70000, 90000],
'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [33]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [34]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [35]:
pd.merge(employees, salaries, on='employee_id', how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [36]:
pd.merge(employees, salaries, on='employee_id', how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [37]:
pd.merge(employees, salaries, on='employee_id', how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [38]:
pd.merge(employees, salaries, on='employee_id', how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [39]:
df1 = pd.DataFrame({
'A': ['A0', 'A1', 'A2'],
'B': ['B0', 'B1', 'B2'],
'C': ['CO', 'C1', 'C2']
})
df2 = pd.DataFrame({
'A': ['A3', 'A4', 'A5'],
'B': ['B3', 'B4', 'B5'],
'C': ['C3', 'C4', 'C5']
})

In [40]:
pd.concat([df1, df2])

    A   B   C
0  A0  B0  CO
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [41]:
pd.concat([df1, df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  CO  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [42]:
df1 = pd.DataFrame({
'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
'score': [85, 90, 75]
}, index=[2, 3, 4] )

In [43]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [44]:
df2

   score
2     85
3     90
4     75

In [45]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [46]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

In [47]:
data = {
'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
'Store': ['S1', 'S1', 'S2', 'S2', 'S1', '52', '52', 'S1'],
'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
'Date': pd.date_range( '2023-01-01', periods=8)
}

df= pd.DataFrame(data)

In [48]:
# Group by category and calculate the sum of sales
cat=df.groupby('Category')['Sales'].sum()

In [49]:
# Group by Store and calculate the sum of sales
store=df.groupby('Store')['Sales'].sum()
print(cat)

Category
A    570
B    930
Name: Sales, dtype: int64

In [50]:
# Group by multiple columns
# Group by Category and Store
multi=df.groupby(['Category', 'Store'])['Sales'].sum()
print(multi)

Category  Store
A         52       200
          S1       220
          S2       150
B         52       180
          S1       500
          S2       250
Name: Sales, dtype: int64

In [51]:
df['Sales'].mean()

np.float64(187.5)

In [52]:
df['Sales'].agg(['sum','mean','max','min','count','std','median'])

sum       1500.000000
mean       187.500000
max        300.000000
min        100.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

# Pivot Tables

In [53]:
data = {
'Date': pd.date_range('2023-01-01', periods=20),
'Product': ['A', 'B', 'C', 'D'] * 5,
'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
'Sales': np. random. randint (100, 1000, 20),
'Units': np. random. randint(10, 100, 20),
'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}
df = pd. DataFrame(data)


df ['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt. quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    812     55   John  January      Q1
1  2023-01-02       B   West    927     64   Mary  January      Q1
2  2023-01-03       C  North    906     80    Bob  January      Q1
3  2023-01-04       D  South    842     26  Alice  January      Q1
4  2023-01-05       A   East    965     20   John  January      Q1
5  2023-01-06       B   West    124     57   Mary  January      Q1
6  2023-01-07       C  North    145     72    Bob  January      Q1
7  2023-01-08       D  South    386     47  Alice  January      Q1
8  2023-01-09       A   East    110     67   John  January      Q1
9  2023-01-10       B   West    636     75   Mary  January      Q1
10 2023-01-11       C  North    687     63    Bob  January      Q1
11 2023-01-12       D  South    100     62  Alice  January      Q1
12 2023-01-13       A   East    938     60   John  January      Q1
13 2023-01-14       B   West    711     10   Mary  January      Q1
14 2023-01-15       C  North    290     42    Bob  January      Q1
15 2023-01-16       D  South    194     96  Alice  January      Q1
16 2023-01-17       A   East    686     31   John  January      Q1
17 2023-01-18       B   West    810     72   Mary  January      Q1
18 2023-01-19       C  North    941     46    Bob  January      Q1
19 2023-01-20       D  South    253     88  Alice  January      Q1

In [54]:
pd.pivot_table(df, values='Sales', index='Region', columns='Product', aggfunc='sum')

Product       A       B       C       D
Region
East     3511.0     NaN     NaN     NaN
North       NaN     NaN  2969.0     NaN
South       NaN     NaN     NaN  1775.0
West        NaN  3208.0     NaN     NaN

In [55]:

pivot2=pd.pivot_table(df, values=['Sales','Units'], index='Region', columns='Product', aggfunc='sum')
pivot2

          Sales                          Units
Product       A       B       C       D      A      B      C      D
Region
East     3511.0     NaN     NaN     NaN  233.0    NaN    NaN    NaN
North       NaN     NaN  2969.0     NaN    NaN    NaN  303.0    NaN
South       NaN     NaN     NaN  1775.0    NaN    NaN    NaN  319.0
West        NaN  3208.0     NaN     NaN    NaN  278.0    NaN    NaN

In [56]:
pd.crosstab(df['Region'], df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

# Operations

In [57]:
# Data Frame Basic Operations
df1=pd.DataFrame({
     'A': [1,2,3,4,5],
     'B': [10,20,30,40,50],
     'C': [100,200,300,400,500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [58]:
df1.shape

(5, 3)

In [59]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [60]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [61]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [62]:
def square(x):
    return x**2

In [63]:
df["D"]=df1["B"].apply(square)
df

         Date Product Region  Sales  Units    Rep    Month Quarter       D
0  2023-01-01       A   East    812     55   John  January      Q1   100.0
1  2023-01-02       B   West    927     64   Mary  January      Q1   400.0
2  2023-01-03       C  North    906     80    Bob  January      Q1   900.0
3  2023-01-04       D  South    842     26  Alice  January      Q1  1600.0
4  2023-01-05       A   East    965     20   John  January      Q1  2500.0
5  2023-01-06       B   West    124     57   Mary  January      Q1     NaN
6  2023-01-07       C  North    145     72    Bob  January      Q1     NaN
7  2023-01-08       D  South    386     47  Alice  January      Q1     NaN
8  2023-01-09       A   East    110     67   John  January      Q1     NaN
9  2023-01-10       B   West    636     75   Mary  January      Q1     NaN
10 2023-01-11       C  North    687     63    Bob  January      Q1     NaN
11 2023-01-12       D  South    100     62  Alice  January      Q1     NaN
12 2023-01-13       A   East    938     60   John  January      Q1     NaN
13 2023-01-14       B   West    711     10   Mary  January      Q1     NaN
14 2023-01-15       C  North    290     42    Bob  January      Q1     NaN
15 2023-01-16       D  South    194     96  Alice  January      Q1     NaN
16 2023-01-17       A   East    686     31   John  January      Q1     NaN
17 2023-01-18       B   West    810     72   Mary  January      Q1     NaN
18 2023-01-19       C  North    941     46    Bob  January      Q1     NaN
19 2023-01-20       D  South    253     88  Alice  January      Q1     NaN

# Finding Data

In [64]:
# Go to data sets on Kaggle

# Feature etrction feature

In [65]:
df=pd.read_csv(r"anime.csv")

In [66]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [67]:
# Make a new column for episode count
df.loc[2]['Title']

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [68]:
def extract_episodes(txt):
     check=False
     data=""
     for i in txt:
          if i==")":
               break
          if check:
               data+=i
          if i=='(':
               check=True
     return data

In [69]:
df['Episodes'] = df['Title'].apply(extract_episodes)

In [70]:
df

    Rank                                              Title  Score Episodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64 eps
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24 eps
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13 eps
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   51 eps
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   10 eps
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04   51 eps
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04    1 eps
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04  148 eps
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04   13 eps
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03   13 eps
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03    2 eps
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02  110 eps
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99   13 eps
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99   13 eps
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98   12 eps
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94  201 eps
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94    1 eps
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93   22 eps
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93   24 eps
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91   25 eps
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91    1 eps
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89    1 eps
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88    7 eps
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88   14 eps
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87   74 eps
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84    1 eps
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84    1 eps
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83   12 eps
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83    1 eps
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82   24 eps
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82   23 eps
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81   12 eps
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81   26 eps
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80   13 eps
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80   16 eps
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79   11 eps
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79    1 eps
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79   11 eps
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78   10 eps
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78    1 eps
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77   26 eps
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77   12 eps
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76   75 eps
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75   26 eps
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75   26 eps
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74   24 eps
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73   10 eps
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72   12 eps
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71   12 eps
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71    4 eps

In [71]:
df['Episodes']=df['Episodes'].str.replace(" eps","").str.strip()

In [72]:
df

    Rank                                              Title  Score Episodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04       51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04        1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04      148
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04       13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03       13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03        2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02      110
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99       13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99       13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98       12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94      201
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94        1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93       22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93       24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91       25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91        1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89        1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88        7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88       14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87       74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84        1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84        1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83       12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83        1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82       24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82       23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81       12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81       26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80       13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80       16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79       11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79        1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79       11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78       10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78        1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77       26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77       12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76       75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75       26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75       26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74       24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73       10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72       12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71       12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71        4

In [73]:
# Make a new column for time stamp

In [74]:
df.loc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [77]:
# Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview
# Extract Apr 2009 - Jul 2010
def extraction_time(txt):
     check=False
     data=""
     for i in range(len(txt)):
          if check:
               for j in range(i,i+19):
                    data+=txt[j]
               return data
          if txt[i]==")":
               check=True

In [78]:
df['Total Time']=df['Title'].apply(extraction_time)

In [80]:
df.head()

,Rank,Title,Score,Episodes,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [81]:
def calculate_months(range_str):
    start, end = range_str.split(" - ")
    start_date = pd.to_datetime(start)
    end_date = pd.to_datetime(end)
    
    return (end_date.year - start_date.year) * 12 + (end_date.month - start_date.month)

In [82]:
df['Months']=df['Total Time'].apply(calculate_months)

In [83]:
df.head()

,Rank,Title,Score,Episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,3

In [84]:
# Which anime has highest score
df[df['Score']==df['Score'].max()]

,Rank,Title,Score,Episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,15

In [86]:
# top 5 highest scoring anime
df['Score'].head()

0    9.10
1    9.07
2    9.06
3    9.06
4    9.05
Name: Score, dtype: float64